[tool.poetry]
name = "django-demo"
version = "0.1.0"
description = ""
authors = ["Holegots <fuergaosi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1.1"
gunicorn = "^20.1.0"
uvicorn = "^0.18.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
